name: Auto Report from Remote

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pull Remote
        if: always()
        run: "python -u pull_remote.py"

      - name: Configure OpenVPN
        env:
          users: ${{ secrets.USERS }}
        run: |
          sudo apt update
          sudo apt-get --assume-yes --no-install-recommends install openvpn
          python3 ovpn.py
          touch vpn.log

      - name: Connect and Test OpenVPN Connection
        if: always()
        run: if [[ $disable_openvpn != true ]] ; then sudo ./ovpn.sh ; fi
        env:
          disable_openvpn: ${{ secrets.DISABLE_OPENVPN }}

      - name: Report
        if: always()
        env:
          users: ${{ secrets.USERS }}
          https_proxy: ${{ secrets.HTTPS_PROXY }}
        run: "python -u run_remote.py"

      - name: Kill OpenVPN Connection
        if: always()
        run: |
          sudo chmod 777 vpn.log
          if [[ $disable_openvpn != true ]] ; then sudo killall openvpn ; fi
        env:
          disable_openvpn: ${{ secrets.DISABLE_OPENVPN }}

      - name: Upload VPN logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: VPN logs
          path: vpn.log